---
substitutions:
  wifi_reboot_timeout: 5min
  wifi_hidden: "false"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: $wifi_hidden
  reboot_timeout: $wifi_reboot_timeout
  ap:
    password: !secret ap_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_signal_sensor

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: ip_address
    ssid:
      name: "SSID"
      id: wifi_ssid
    bssid:
      name: "BSSID"
      id: wifi_bssid

captive_portal:
