---
substitutions:
  wifi_reboot_timeout: 5min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: $wifi_reboot_timeout
  ap:
    password: !secret ap_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_signal_sensor

captive_portal:
