---
binary_sensor:
  - <<: !include
      file: button.yaml
      vars:
        number: "1"
        gpio_pin: GPIO16
  - <<: !include
      file: button.yaml
      vars:
        number: "2"
        gpio_pin: GPIO5
  - <<: !include
      file: button.yaml
      vars:
        number: "3"
        gpio_pin: GPIO4

output:
  - platform: gpio
    id: relay1
    pin: GPIO13
  - platform: gpio
    id: relay2
    pin: GPIO12
  - platform: gpio
    id: relay3
    pin: GPIO14

switch:
  - platform: output
    id: switch1
    output: relay1
    name: "Relay 1"
  - platform: output
    id: switch2
    output: relay2
    name: "Relay 2"
  - platform: output
    id: switch3
    output: relay3
    name: "Relay 3"

light:
  - platform: status_led
    name: Status LED
    disabled_by_default: true
    pin:
      number: GPIO2
      inverted: true

substitutions:
  button_1_hold: 2s
  button_2_hold: 2s
  button_3_hold: 2s
