---
esphome:
  name: $name
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    # version: "4.4.0"
    # sdkconfig_options:
    #   CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
    #   CONFIG_ESP_CONSOLE_UART_CUSTOM: y
    #   CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: y

packages:
  base: !include common-base.yaml

logger:
#   deassert_rts_dtr: true
