---
substitutions:
  board: esp01_1m
  esp8266_early_pin_init: "true"
  esp8266_restore_from_flash: "true"

esp8266:
  board: "${board}"
  restore_from_flash: ${esp8266_restore_from_flash}
  early_pin_init: ${esp8266_early_pin_init}

packages:
  base: !include common-base.yaml
