---
substitutions:
  board: esp01_1m
  esp8266_early_pin_init: "true"

esp8266:
  board: "${board}"
  restore_from_flash: true
  early_pin_init: ${esp8266_early_pin_init}

packages:
  base: !include common-base.yaml
  wifi: !include common/wifi.yaml
