substitutions:
  name: back-door-switch
  friendly_name: Back Door Switch
  wifi_reboot_timeout: 5min
  light_name: Back Door

packages:
  switch: !include modules/devices/athom-sw01.yml

logger:
  baud_rate: 0
