---
substitutions:
  name: olimex-bt-proxy-lounge
  friendly_name: Olimex BT Proxy Lounge
  board: esp32-evb

packages:
  common: !include modules/common-esp32.yaml

logger:
# level: INFO

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0

esp32_ble_tracker:
  scan_parameters:
    active: false  # default true
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  id: my_bluetooth_proxy
  active: true

time:
  - id: !extend sntp_time
    on_time:
      - cron: 0 0 0 * * *
        then:
          - button.press: restart_button
