---
substitutions:
  name: olimex-bt-proxy-garage
  friendly_name: Olimex BT Proxy Garage
  board: esp32-poe-iso

packages:
  - !include modules/common-esp32.yaml
  - !include modules/common/bluetooth-proxy.yaml

logger:
  # level: INFO
  level: DEBUG
  # level: VERY_VERBOSE

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12

esp32_ble_server:
  model: PoE-ISO
  manufacturer: Olimex

time:
  - id: !extend sntp_time
    on_time:
      - cron: 0 0 0 * * *
        then:
          - button.press: restart_button
