---
substitutions:
  name: ct-clamp
  friendly_name: CT Clamp
  wifi_reboot_timeout: 0s
  ip: "10.6.6.82"

packages:
  common: !include modules/common-32-idf.yaml
  wifi: !include modules/common/wifi.yaml

  gpio0: !include modules/gpio0.yaml

light:
  - platform: status_led
    pin: GPIO2
    name: 'Status LED'

sensor:
  - platform: adc
    id: analog
    pin: GPIO34
    attenuation: 11db
    update_interval: never
    raw: true

  - platform: ct_clamp
    name: CT Measured Current
    id: current
    sensor: analog
    sample_duration: 200ms
    update_interval: 1000ms
    filters:
      - lambda: "return x < 20.0f ? 0.0f : x;"
      - calibrate_linear:
          - 0 -> 0
          - 9 ->  0.03
          - 365 -> 9.41
          # - 116 -> 3.0
          # - 450 -> 11.27
      - lambda: "return clamp(x, 0.0f, 100.0f);"
