---
substitutions:
  name: dining-switch
  friendly_name: Dining Switch
  ip: "10.6.6.174"
  wifi_reboot_timeout: 0s

packages:
  common: !include modules/common-8266.yaml
  zemismart: !include modules/devices/zemismart/3gang.yaml
