substitutions:
  name: "energy-monitor-6"
  friendly_name: "Energy Monitor 6"

  bl0906_tx_pin: GPIO7
  bl0906_rx_pin: GPIO8
  button_pin:    GPIO9
  led_pin:       GPIO10

packages:
  common: !include modules/common-32-c3.yaml
  wifi: !include modules/common/wifi.yaml

preferences:
  flash_write_interval: 5min

logger:
  hardware_uart: UART0

web_server:

uart:
  tx_pin: ${bl0906_tx_pin}
  rx_pin: ${bl0906_rx_pin}
  baud_rate: 19200
  id: uart_bl0906

light:
  - platform: status_led
    name: "Status LED"
    id: blue_led
    disabled_by_default: true
    pin: ${led_pin}

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true

sensor:
  - platform: bl0906
    update_interval: 5s
    frequency:
      name: 'Frequency'
    temperature:
      name: 'Temperature'
    voltage:
      name: 'Voltage'
    channel_1:
      power: Lights Power
      energy: Lights Energy
    channel_2:
      power: Cooktop Power
      energy: Cooktop Energy
    channel_3:
      power: Oven Power
      energy: Oven Energy
    channel_4:
      power: Lounge AC Power
      energy: Lounge AC Energy
    channel_5:
      power: Hot Water Power
      energy: Hot Water Energy
    channel_6:
      power: EV Power
      energy: EV Energy
