---
substitutions:
  name: garage-switch
  friendly_name: Garage Switch
  ip: "10.6.6.184"
  wifi_reboot_timeout: 0s

packages:
  common: !include modules/common-esp8266.yaml
  wifi: !include modules/common/wifi.yaml
  zemismart: !include modules/devices/zemismart/3gang.yaml
