---
substitutions:
  name: kayas-switch
  friendly_name: Kaya's Switch
  ip: "10.6.6.149"
  wifi_reboot_timeout: 0s

packages:
  common: !include modules/common-8266.yaml
  zemismart: !include modules/devices/zemismart/3gang.yaml
