substitutions:
  name: kayas-switch
  friendly_name: Kaya's Switch
  ip: '10.6.6.149'
  wifi_reboot_timeout: 0s
  switch_relay_1: "false"
  switch_relay_2: "false"
  switch_relay_3: "false"
  button_3_hold: 1s

packages:
  zemismart: !include modules/devices/zemismart/3gang.yaml
