---
substitutions:
  name: kitchen-light-1
  friendly_name: Kitchen Light 1
  light_name: Kitchen 1
  ip: '10.6.6.175'
  wifi_reboot_timeout: 0s

packages:
  light: !include modules/devices/athom-rgbct-light.yaml
