---
substitutions:
  name: lounge-light-2
  friendly_name: Lounge Light 2
  light_name: Lounge 2
  ip: '10.6.6.216'
  wifi_reboot_timeout: 0s
  api_timeout: 0s

packages:
  light: !include modules/devices/kogan-cwww-light.yaml
