---
substitutions:
  name: lounge-light-1
  friendly_name: Lounge Light 1
  light_name: Lounge 1
  ip: '10.6.6.215'
  wifi_reboot_timeout: 0s
  api_timeout: 0s

packages:
  light: !include modules/devices/kogan-cwww-light.yaml
