---
substitutions:
  name: lounge-light-1
  friendly_name: Lounge Light 1
  light_name: Lounge 1
  ip: '10.6.6.87'
  wifi_reboot_timeout: 0s
  api_timeout: 0s

packages:
  light: !include modules/devices/athom-rgbct-light.yaml

esp8266:
  restore_from_flash: false
