substitutions:
  name: lounge-switch
  friendly_name: Lounge Switch
  ip: '10.6.6.155'
  wifi_reboot_timeout: 0s
  switch_relay_1: "false"
  switch_relay_2: "false"
  switch_relay_3: "false"

packages:
  zemismart: !include modules/devices/zemismart/3gang.yaml

  wizmote: !include modules/wizmote.yaml
