---
substitutions:
  name: lounge-ac
  friendly_name: Lounge AC
  ip: "10.6.6.132"
  wifi_reboot_timeout: 5min
  climate_name: Lounge

packages:
  common: !include modules/common-esp8266.yaml
  wifi: !include modules/common/wifi.yaml
  panasonic: !include modules/devices/panasonic-ac.yaml
