---
substitutions:
  name: lounge-switch
  friendly_name: Lounge Switch
  ip: "10.6.6.155"
  wifi_reboot_timeout: 0s

packages:
  common: !include modules/common-8266.yaml
  zemismart: !include modules/devices/zemismart/3gang.yaml

  wizmote: !include modules/wizmote.yaml
