substitutions:
  name: master-light-2
  friendly_name: Master Light 2
  light_name: Master 2
  ip: '10.6.6.218'
  wifi_reboot_timeout: 0s

packages:
  light: !include modules/devices/kogan-cwww-light.yaml
