---
substitutions:
  name: master-heater
  friendly_name: Master Heater
  ip: "10.6.6.227"
  wifi_reboot_timeout: 5min

packages:
  common: !include modules/common-8266.yaml
  wifi: !include modules/common/wifi.yaml
  heater: !include modules/devices/kogan-heater-black.yaml

# packages override order doesn't work.
logger:
  baud_rate: 0
  # level: VERY_VERBOSE
  logs:
    api.service: DEBUG
    scheduler: DEBUG
