---
substitutions:
  name: rd6018
  friendly_name: RD6018
  board: esp12e

packages:
  common: !include modules/common-8266.yaml
  wifi: !include modules/common/wifi.yaml

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

modbus:
  - id: main_modbus

modbus_controller:
  - id: main_controller
    modbus_id: main_modbus
    address: 0x01
    update_interval: 10s

sensor:
  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Internal Temperature"
    register_type: holding
    address: 4
    register_count: 2
    bitmask: 0xFFFF
    value_type: U_DWORD
    unit_of_measurement: °C
    state_class: measurement
    device_class: temperature
    lambda: |
      return data[item->offset + 1] == 0 ? x : -x;

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "External Temperature"
    register_type: holding
    address: 34
    register_count: 2
    bitmask: 0xFFFF
    value_type: U_DWORD
    unit_of_measurement: °C
    state_class: measurement
    device_class: temperature
    lambda: |
      return data[item->offset + 1] == 0 ? x : -x;

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Output Voltage"
    register_type: holding
    address: 10
    value_type: U_WORD
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Output Current"
    register_type: holding
    address: 11
    value_type: U_WORD
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Output Energy"
    register_type: holding
    address: 12
    value_type: U_WORD
    unit_of_measurement: Ah
    state_class: total
    accuracy_decimals: 2
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Output Power"
    address: 13
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Input Voltage"
    register_type: holding
    address: 14
    value_type: U_WORD
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Energy"
    register_type: holding
    address: 40
    value_type: U_DWORD
    unit_of_measurement: Wh
    state_class: total
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

switch:
  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Keypad Lock"
    address: 15
    register_type: holding
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Power"
    address: 18
    register_type: holding
    bitmask: 1

number:
  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Voltage Setting"
    mode: box
    address: 8
    value_type: U_WORD
    min_value: 0.01
    max_value: 60.0
    step: 0.01
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Current Setting"
    mode: box
    address: 9
    value_type: U_WORD
    min_value: 0.01
    max_value: 18.0
    step: 0.01
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Voltage Protection"
    mode: box
    entity_category: config
    address: 82
    value_type: U_WORD
    min_value: 0.01
    max_value: 60.0
    step: 0.01
    multiply: 100

  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Current Protection"
    mode: box
    entity_category: config
    address: 83
    value_type: U_WORD
    min_value: 0.01
    max_value: 18.0
    step: 0.01
    multiply: 100

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: main_controller
    name: "Battery Mode"
    address: 32
    register_type: holding
    bitmask: 1
