substitutions:
  name: taikis-light
  friendly_name: Taiki's Light
  ip: '10.6.6.75'
  wifi_reboot_timeout: 0s
  light_name: Taiki's Room

packages:
  light: !include modules/devices/athom-rgbct-light.yml
