---
substitutions:
  api_reboot_timeout: 15min

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

ota:
  - platform: esphome
    id: ota_esphome

api:
  reboot_timeout: $api_reboot_timeout
  encryption:
    key: !secret api_encryption_key

logger:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - !secret sntp_server

sensor: !include_dir_list ../sensors
binary_sensor: !include_dir_list ../binary_sensors
button: !include_dir_list ../buttons
