---
substitutions:
  name: dishwasher-plug
  friendly_name: Dishwasher Plug
  restore_mode: ALWAYS_ON
  zero_power_below: "5"

packages:
  common: !include ../../templates/athom/athom-smart-plug-v2.yaml
