---
substitutions:
  name: ensuite-switch
  friendly_name: Ensuite
  wifi_reboot_timeout: 5min

packages:
  switch: !include ../../templates/athom/athom-sw03-bathroom-switch.yaml

logger:
  baud_rate: 0
