---
substitutions:
  name: garage-switch
  friendly_name: Garage Switch
  ip: "10.6.6.184"
  wifi_reboot_timeout: 0s

packages:
  common: !include ../../common/platforms/common-esp8266.yaml
  wifi: !include ../../common/wifi.yaml
  zemismart: !include ../../templates/zemismart/3gang.yaml
