---
substitutions:
  name: kayas-switch
  friendly_name: Kaya's Switch
  ip: "10.6.6.149"
  wifi_reboot_timeout: 0s

packages:
  common: !include ../../common/platforms/common-esp8266.yaml
  wifi: !include ../../common/wifi.yaml
  zemismart: !include ../../templates/zemismart/3gang.yaml
