---
substitutions:
  name: taikis-switch
  friendly_name: Taiki's Switch
  ip: "10.6.6.119"
  wifi_reboot_timeout: 0s

packages:
  common: !include ../../common/platforms/common-esp8266.yaml
  wifi: !include ../../common/wifi.yaml
  zemismart: !include ../../templates/zemismart/3gang.yaml
