---
substitutions:
  name: lounge-ac
  friendly_name: Lounge AC
  ip: "10.6.6.132"
  wifi_reboot_timeout: 5min
  climate_name: Lounge

packages:
  common: !include ../../common/platforms/common-esp8266.yaml
  wifi: !include ../../common/wifi.yaml
  panasonic: !include ../../templates/other/panasonic-ac.yaml
