---
packages:
  common: !include ../common-8266.yaml
  wifi: !include ../common/wifi.yaml

binary_sensor:
  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
    name: "Button 1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: "Button 2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: "Button 3"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - fan.toggle: fan3

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1
  - platform: gpio
    pin: GPIO4
    id: relay2
  - platform: gpio
    pin: GPIO15
    id: relay3

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: gpio
    pin: GPIO16
    inverted: true
    id: button_led1
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: button_led2
  - platform: gpio
    pin: GPIO1
    inverted: true
    id: button_led3

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "Heat Lamps"
    id: light1
    output: relay1
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

  - platform: binary
    name: "${friendly_name}"
    id: light2
    output: relay2
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2

  # - platform: binary
  #   name: "Light 3"
  #   id: light3
  #   output: relay3
  #   on_turn_on:
  #     - light.turn_on: led3
  #   on_turn_off:
  #     - light.turn_off: led3

  # Button LEDs
  - platform: binary
    name: "LED1"
    disabled_by_default: true
    id: led1
    output: button_led1
    # default_transition_length: 500ms

  - platform: binary
    name: "LED2"
    disabled_by_default: true
    id: led2
    output: button_led2
    # default_transition_length: 500ms

  - platform: binary
    name: "LED3"
    disabled_by_default: true
    id: led3
    output: button_led3
    # default_transition_length: 500ms

fan:
  - platform: binary
    name: "${friendly_name}"
    id: fan3
    output: relay3
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - light.turn_on: led3
    on_turn_off:
      - light.turn_off: led3
