---
substitutions:
  restore_mode: RESTORE_DEFAULT_ON
  light_name: "${friendly_name}"
  board: esp8285

packages:
  common: !include ../common-8266.yaml
  wifi: !include ../common/wifi.yaml

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5

light:
  - platform: rgbww
    restore_mode: ${restore_mode}
    color_interlock: true
    name: "${light_name}"
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    default_transition_length: 200ms
