---
substitutions:
  restore_mode: RESTORE_DEFAULT_OFF

logger:
  baud_rate: 0
  deassert_rts_dtr: true

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
    name: "${friendly_name} Power Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

sensor:
  - platform: cse7766
    update_interval: 5s
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Power"
      id: power

  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO3
    id: relay
    restore_mode: ${restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} Blue LED"
    pin:
      inverted: true
      number: GPIO8
