---
substitutions:
  board: esp8285
  restore_mode: ALWAYS_OFF
  zero_power_below: "0"

packages:
  common: !include ../common-8266.yaml

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

sensor:
  - platform: cse7766
    update_interval: 10s
    current:
      name: "Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"
      filters:
        - lambda: |-
            if (x < ${zero_power_below}) {
              return 0;
            } else {
              return x;
            }
    energy:
      name: "Energy"
      unit_of_measurement: kWh
      filters:
        - multiply: 0.001

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO12
    restore_mode: ${restore_mode}
    id: relay

light:
  - platform: status_led
    name: "Status LED"
    pin:
      number: GPIO13
      inverted: true
