---
substitutions:
  restore_mode: RESTORE_DEFAULT_OFF
  zero_power_below: "0"

packages:
  common: !include ../common-esp32c3.yaml
  wifi: !include ../common/wifi.yaml

esp32:
  partitions: modules/partitions.arduino.csv


api:
  encryption: !remove

preferences:
  flash_write_interval: 5min

logger:
  baud_rate: 0
  deassert_rts_dtr: true

uart:
  rx_pin: GPIO20
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
    name: "Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

sensor:
  - platform: cse7766
    current:
      name: "Current"
      filters:
        - throttle_average: 10s

    voltage:
      name: "Voltage"
      filters:
        - throttle_average: 10s

    power:
      name: "Power"
      id: power
      filters:
        - throttle_average: 10s
        - lambda: |-
            if (x < ${zero_power_below}) {
              return 0;
            } else {
              return x;
            }

    energy:
      name: Energy
      id: energy_sensor
      unit_of_measurement: kWh
      filters:
        - multiply: 0.001
        - throttle: 10s

    apparent_power:
      name: Apparent Power
      id: apparent_power_sensor
      disabled_by_default: true
      filters:
        - throttle: 10s

    reactive_power:
      name: Reactive Power
      id: reactive_power_sensor
      disabled_by_default: true
      icon: mdi:flash
      filters:
        - throttle: 10s

    power_factor:
      name: Power Factor
      id: power_factor_sensor
      disabled_by_default: true
      filters:
        - throttle: 10s

switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO3
    id: relay
    restore_mode: ${restore_mode}

light:
  - platform: status_led
    name: Status LED
    id: blue_led
    icon: mdi:lightbulb-outline
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO8
