---
substitutions:
  light_name: "${friendly_name}"
  board: esp8285

packages:
  common: !include ../common-esp8266.yaml
  wifi: !include ../common/wifi.yaml

binary_sensor:
  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: "Button 1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: "Button 2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1
  - platform: gpio
    pin: GPIO4
    id: relay2

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: led1
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: led2

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "1"
    id: light1
    output: relay1
    on_turn_on:
      - light.turn_on: light1_led
    on_turn_off:
      - light.turn_off: light1_led
  - platform: binary
    name: "2"
    id: light2
    output: relay2
    on_turn_on:
      - light.turn_on: light2_led
    on_turn_off:
      - light.turn_off: light2_led

  # Button LEDs
  - platform: monochromatic
    name: "LED1"
    disabled_by_default: true
    id: light1_led
    output: led1
    default_transition_length: 500ms
  - platform: monochromatic
    name: "LED2"
    disabled_by_default: true
    id: light2_led
    output: led2
    default_transition_length: 500ms
