---
substitutions:
  light_name: "${friendly_name}"
  board: esp8285

packages:
  common: !include ../common-8266.yaml

binary_sensor:
  # Switch
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: "${friendly_name} Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.switch
              data:
                device: ${name}
                action: click
          - light.toggle: light1
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.switch
              data:
                device: ${name}
                action: double_click
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

output:
  # Relay
  - platform: gpio
    pin: GPIO13
    id: relay1

  # Button LED (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: button_led1

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relay
  - platform: binary
    name: "${light_name}"
    id: light1
    output: relay1
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

  # Button LED
  - platform: monochromatic
    name: "${friendly_name} LED"
    disabled_by_default: true
    id: led1
    output: button_led1
    default_transition_length: 500ms
