---
substitutions:
  climate_name: ${friendly_name}

packages:
  common: !include ../common-8266.yaml

external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

uart:
  id: ac_uart
  tx_pin: 14
  rx_pin: 12
  baud_rate: 9600
  parity: even
  stop_bits: 1
  data_bits: 8

climate:
  - platform: panasonic_ac
    type: cnt
    name: ${climate_name}
    horizontal_swing_select:
      name: ${friendly_name} Horizontal Swing Mode
    vertical_swing_select:
      name: ${friendly_name} Vertical Swing Mode
    outside_temperature:
      name: ${friendly_name} Outside Temperature
    current_temperature_sensor: lounge_temp

sensor:
  - platform: homeassistant
    id: lounge_temp
    entity_id: sensor.lounge_atc_temperature
