---
substitutions:
  climate_name: ${friendly_name}

external_components:
  source: github://DomiStyle/esphome-panasonic-ac
  components: [panasonic_ac]

uart:
  id: ac_uart
  tx_pin: 14
  rx_pin: 12
  baud_rate: 9600
  parity: even
  stop_bits: 1
  data_bits: 8

climate:
  - platform: panasonic_ac
    type: cnt
    name: ${climate_name}
    horizontal_swing_select:
      name: Horizontal Swing Mode
    vertical_swing_select:
      name: Vertical Swing Mode
    outside_temperature:
      name: Outside Temperature
    current_temperature_sensor: lounge_temp
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

sensor:
  - platform: homeassistant
    id: lounge_temp
    entity_id: sensor.lounge_atc_temperature
