---
substitutions:
  name: sdm230
  friendly_name: SDM230
  ip: "10.6.6.226"

packages:
  common: !include ../../common/platforms/common-esp8266.yaml
  wifi: !include ../../common/wifi.yaml

logger:
  # level: DEBUG
  # level: VERY_VERBOSE
  # level: VERBOSE
  baud_rate: 0
  # levels:

uart:
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3

modbus:
  flow_control_pin: GPIO5

sensor:
  - platform: sdm_meter
    update_interval: 10s
    address: 0x02
    phase_a:
      voltage:
        name: SDM Voltage
      current:
        name: SDM Current
      active_power:
        name: SDM Active Power
      apparent_power:
        name: SDM Apparent Power
      reactive_power:
        name: SDM Reactive Power
      power_factor:
        name: SDM Power Factor
      phase_angle:
        name: SDM Phase Angle
    frequency:
      name: SDM Frequency
    import_active_energy:
      name: SDM Import Active Energy
    export_active_energy:
      name: SDM Export Active Energy
    import_reactive_energy:
      name: SDM Import Reactive Energy
    export_reactive_energy:
      name: SDM Export Reactive Energy

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x00
#     id: controller_voltage
#     name: SDM Voltage
#     unit_of_measurement: V
#     device_class: voltage
#     accuracy_decimals: 2
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x06
#     id: controller_current
#     name: SDM Current
#     unit_of_measurement: A
#     device_class: current
#     accuracy_decimals: 3
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x0C
#     id: controller_active_power
#     name: SDM Active Power
#     unit_of_measurement: W
#     device_class: power
#     accuracy_decimals: 2
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x12
#     id: controller_apparent_power
#     name: SDM Apparent Power
#     unit_of_measurement: VA
#     device_class: power
#     accuracy_decimals: 2
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x18
#     id: controller_reactive_power
#     name: SDM Reactive power
#     unit_of_measurement: VAr
#     device_class: power
#     accuracy_decimals: 2
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x1E
#     id: controller_power_factor
#     name: SDM Power Factor
#     accuracy_decimals: 3
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x24
#     id: controller_phase_angle
#     name: SDM Phase Angle
#     unit_of_measurement: °
#     icon: mdi:flash
#     accuracy_decimals: 3
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x46
#     id: controller_frequency
#     name: SDM Frequency
#     unit_of_measurement: Hz
#     icon: mdi:current-ac
#     accuracy_decimals: 2
#     state_class: measurement
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x48
#     id: controller_import_active_energy
#     name: SDM Import Active Energy
#     unit_of_measurement: kWh
#     accuracy_decimals: 2
#     state_class: total_increasing
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x4A
#     id: controller_export_active_energy
#     name: SDM Export Active Energy
#     unit_of_measurement: kWh
#     accuracy_decimals: 2
#     state_class: total_increasing
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x4C
#     id: controller_import_reactive_energy
#     name: SDM Import Reactive Energy
#     unit_of_measurement: kVAr
#     accuracy_decimals: 2
#     state_class: total_increasing
#     value_type: FP32

#   - platform: modbus_controller
#     modbus_functioncode: read_input_registers
#     address: 0x00
#     offset: 0x4E
#     id: controller_export_reactive_energy
#     name: SDM Export Reactive Energy
#     unit_of_measurement: kVAr
#     accuracy_decimals: 2
#     state_class: total_increasing
#     value_type: FP32

# modbus_controller:
#   id: modcontrol
#   address: 0x02
#   update_interval: 10s
#   command_throttle: 10s
