---
substitutions:
  board: esp8285

packages:
  common: !include ../../common/platforms/common-esp8266.yaml

# Dont actually use deep sleep,
# but this should stop unavailable when the
# kettle is removed from the base
# or turned off at the wall
deep_sleep:

logger:
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

tuya:

switch:
  - platform: tuya
    switch_datapoint: 1
    name: None
    icon: mdi:kettle

  - platform: tuya
    switch_datapoint: 103
    name: 103
    icon: mdi:kettle

sensor:
  - platform: tuya
    sensor_datapoint: 5
    name: Current Temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - platform: tuya
    sensor_datapoint: 103
    name: 103
    icon: mdi:kettle

  - platform: tuya
    sensor_datapoint: 101
    name: 101
    icon: mdi:kettle

select:
  - platform: tuya
    enum_datapoint: 102
    options:
      0: 40°C
      1: 50°C
      2: 60°C
      3: 80°C
      4: 90°C
      5: "Off"
    name: Keep Warm

number:
  - platform: tuya
    number_datapoint: 103
    name: 103
    min_value: 0
    max_value: 1
    step: 1
