sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:98:37:B5
    battery_level:
      name: Bathroom ATC Battery Level
    battery_voltage:
      name: Bathroom ATC Battery Voltage
    humidity:
      name: Bathroom ATC Humidity
    temperature:
      name: Bathroom ATC Temperature
