---
sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:92:4D:08
    battery_level:
      name: Ensuite ATC Battery Level
    battery_voltage:
      name: Ensuite ATC Battery Voltage
    humidity:
      name: Ensuite ATC Humidity
    temperature:
      name: Ensuite ATC Temperature
