sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:37:98:A1
    battery_level:
      name: Garage ATC Battery Level
    battery_voltage:
      name: Garage ATC Battery Voltage
    humidity:
      name: Garage ATC Humidity
    temperature:
      name: Garage ATC Temperature
