sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:3D:D5:9D
    battery_level:
      name: Lounge ATC Battery Level
    battery_voltage:
      name: Lounge ATC Battery Voltage
    humidity:
      name: Lounge ATC Humidity
    temperature:
      name: Lounge ATC Temperature
