---
sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:66:2F:EB
    battery_level:
      name: Office ATC Battery Level
    battery_voltage:
      name: Office ATC Battery Voltage
    humidity:
      name: Office ATC Humidity
    temperature:
      name: Office ATC Temperature
