sensor:
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:BC:D5:DC
    battery_level:
      name: Roof Space ATC Battery Level
    battery_voltage:
      name: Roof Space ATC Battery Voltage
    humidity:
      name: Roof Space ATC Humidity
    temperature:
      name: Roof Space ATC Temperature
